In [8]:
import numpy as np

n = 7
m = 5 + 3*n
p = np.zeros((m))
p[5:] = np.zeros((3*n)) + 2
p[7]  = 1
p_3D = p[5:].reshape(3,n,order="F")
p1 = p_3D[:,:3]*0
p2 = p_3D[:,3:]
np.hstack([p1, p2])
p[:5] = [0.1145, 0.325,-0.050,0.65,-0.030]
p[:5]
#print( np.vstack((p2, np.ones(p2.shape[1]))))
print(p.shape[0])

26


In [60]:
heli_points = np.loadtxt('../data/heli_points.txt').T[:3,:]
print(heli_points)
heli_points.reshape(21,order="F")

[[-0.13   0.18   0.43  -0.035 -0.035 -0.035 -0.035]
 [-0.01  -0.01  -0.01  -0.09  -0.18   0.2    0.1  ]
 [ 0.01   0.01   0.01  -0.04  -0.06  -0.05  -0.04 ]]


array([-0.13 , -0.01 ,  0.01 ,  0.18 , -0.01 ,  0.01 ,  0.43 , -0.01 ,
        0.01 , -0.035, -0.09 , -0.04 , -0.035, -0.18 , -0.06 , -0.035,
        0.2  , -0.05 , -0.035,  0.1  , -0.04 ])

In [42]:
detections = np.loadtxt('../data/detections.txt')
detections.shape
l = 351
n = 7
uv = np.zeros((2*l,n))
weights = np.zeros((l,n))
for image_number in range(l):
    uv[2*image_number,:]      = detections[image_number, 1::3]
    uv[2*image_number+1,:]    = detections[image_number, 2::3]
    weights[image_number,:] = detections[image_number, ::3]

print(weights.reshape(351*7))




[1. 1. 1. 1. 1. 0. 1.]


In [4]:
uv = np.zeros((351*2,7))
for i in range(351):
    uv[2*i+1,:] = 1
    
uv

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [46]:
e_u = np.array([[0,5,0,0,0,0,5],[1,1,1,1,1,1,7]])
e_v = np.array([[2,2,2,2,2,2,9],[3,3,3,3,3,3,11]])
r   = np.zeros((1,28))
N = 7
for i in range(2):
    u = e_u[i,:]
    v = e_v[i,:]
    r[:,2*N*i:2*N*i+2*N] = np.hstack((u,v))

 #   r[:,2*N*(i):2*N*(i)+N] = 
r

array([[ 0.,  5.,  0.,  0.,  0.,  0.,  5.,  2.,  2.,  2.,  2.,  2.,  2.,
         9.,  1.,  1.,  1.,  1.,  1.,  1.,  7.,  3.,  3.,  3.,  3.,  3.,
         3., 11.]])

In [7]:
import numpy as np

L = 4
X = np.array([[0,5,0],[5,0,5],[1,1,1],[7,1,7]])
Y = X.reshape(3*L)
angles = Y.reshape((L,3))
angles


array([[0, 5, 0],
       [5, 0, 5],
       [1, 1, 1],
       [7, 1, 7]])