In [32]:
import numpy as np

t = np.array([[1, 0, 3,4,5,6,4,5,6],
              [2, 1, 1,4,5,6,4,5,6],
              [2, 0, 1,4,5,6,4,5,6],
              [4, 0, 1,4,5,6,4,5,6]])

t[:,0:3]

array([[1, 0, 3],
       [2, 1, 1],
       [2, 0, 1],
       [4, 0, 1]])

In [29]:
t[:,np.mod(np.arange(t.shape[1]),2*1)<1]

array([[1, 3, 5, 4, 6],
       [2, 1, 5, 4, 6],
       [2, 1, 5, 4, 6],
       [4, 1, 5, 4, 6]])

In [56]:
t[:, 1:t.shape[1]:3]

array([[0, 5, 5],
       [1, 5, 5],
       [0, 5, 5]])

In [102]:
n = np.zeros((3,182))
n[:,n.shape[1]-1] = 3
w = n[:,2::3]
#n[:,n.shape[1]-1]
w = np.append(w, np.array([n[:,n.shape[1]-1]]).T, axis=1)
#w.shape
w.shape



(3, 61)

In [116]:
d =np.array([[1,1]])
s = np.array([[2,2]])
f = np.zeros((2,2))
f[0,:] = d
f[1,:] = s
f

array([[1., 1.],
       [2., 2.]])

In [11]:
np.sin(np.deg2rad(90))

1.0

In [16]:
def translate_z(z):
    return np.array([[1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 1, z],
                     [0, 0, 0, 1]])

#Rotation definitions
def rotate_x(radians):
    return np.array([[1, 0, 0, 0],
                     [0, np.cos(radians), -np.sin(radians), 0],
                     [0, np.sin(radians), np.cos(radians), 0],
                     [0, 0, 0, 1]])

def rotate_y(radians):
    return np.array([[np.cos(radians), 0, np.sin(radians), 0],
                     [0, 1, 0, 0],
                     [-np.sin(radians), 0, np.cos(radians), 0],
                     [0, 0, 0, 1]])

x_3 = np.array([[2,4,6]])
x_4 = np.array([[2,4,6,1]]).T

n_4 = translate_z(6)@rotate_x(np.deg2rad(15))@rotate_y(np.deg2rad(45))@x_4
n_4


array([[5.65685425],
       [3.1316525 ],
       [9.76732699],
       [1.        ]])

In [27]:
n_3 = np.array([[1, 0, 0, ],
               [0, np.cos(np.deg2rad(15)), -np.sin(np.deg2rad(15))],
                [0, np.sin(np.deg2rad(15)), np.cos(np.deg2rad(15))]])@np.array([[np.cos(np.deg2rad(45)), 0, np.sin(np.deg2rad(45))],
                     [0, 1, 0],
                     [-np.sin(np.deg2rad(45)), 0, np.cos(np.deg2rad(45))]])@x_3.T + np.array([[0,0,6]]).T
n_3

array([[5.65685425],
       [3.1316525 ],
       [9.76732699]])